name: demo
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  reorderables: ^0.6.0
  desktop_multi_window: ^0.2.1
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  image_picker:
  file_picker:
  pull_to_refresh_flutter3:
  provider:
  nested: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/